authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "authentication"

urlpatterns = [

    path('register/',views.SignUpView.as_view(), name="register"),
    path('login/',views.login_view, name="login"),

    #path('logout/',views.logout_view, name="logout"),
   
    
]

django_auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
        

    path('accounts/', include('authentication.urls', namespace='authentication')),

]

authentication/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager, PermissionsMixin
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

'''
model for holding all the users in the club. 
'''
class MyUsersManager(BaseUserManager):

    def create_user(self,first_name,last_name,nat_id,email,phone_number,password):
        '''
        Manages the creation on student instances
        '''
        if not first_name:
            raise ValueError("Full name must be included")
        if not last_name:
            raise ValueError("Please add an admission number")
        if not nat_id:
            raise ValueError("User must have a national_id")
        if not email:
            raise ValueError("Please add the school email address")
        if not phone_number:
            raise ValueError("Please add a phone number")
        if not password:
            raise ValueError("User must have a password")

        user = self.model(
            email=self.normalize_email(email),
            last_name = last_name,
            phone_number = phone_number,
            nat_id=nat_id,
            first_name = first_name,
        )

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self,first_name,last_name,nat_id,email,phone_number,password):
        '''
        Manages the creation of superuser 
        '''
        user = self.create_user(
            first_name=first_name,
            last_name = last_name,
            nat_id = nat_id,                        
            email=self.normalize_email(email=email),
            phone_number=phone_number,
            password=password,
            )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True

        user.save(using=self._db)

        return user

class UserModel(AbstractBaseUser, PermissionsMixin):
    first_name        = models.CharField(max_length=50,null= False)
    last_name        = models.CharField(max_length=50,null= False)
    nat_id         = models.PositiveIntegerField(max_length=8,null= False,unique=True)       
    email            = models.EmailField(verbose_name="email", max_length=100, unique=True)
    phone_number     = models.BigIntegerField(unique=True,null= False)
    date_joined      = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login       = models.DateTimeField(verbose_name='last login', auto_now=True)

    is_admin         = models.BooleanField(default=False)
    is_active        = models.BooleanField(default=True)
    is_staff         = models.BooleanField(default=False)
    is_superuser     = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['nat_id','phone_number','first_name','last_name','password']

    objects = MyUsersManager()

    def __str__(self):
        return self.email

    def has_perm(self,perm, obj=None):
        return True
    
    def has_module_perms(self,app_label):
        return True

users/forms.py
from django import forms
from django.contrib import admin
from django.contrib.auth.models import Group
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import UserModel

class CustomUserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    
    class Meta:
        model = UserModel 
        fields = ("first_name", "last_name","nat_id", "email","phone_number")

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class CustomUserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()
    
    
    class Meta:
        model = UserModel
        fields = ("first_name", "last_name","nat_id", "email","phone_number")

    def clean_password(self):
        return self.initial["password"]


class LoginForm(forms.Form):
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "email",                
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",                
                "class": "form-control"
            }
        ))
    

authentication/views.py
from users.forms import CustomUserCreationForm, LoginForm
from django.views.generic.edit import CreateView

from django.urls import reverse_lazy
from users.forms import CustomUserCreationForm
from users.backends import MyAuthBackend
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib import messages

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "authentication/register.html"

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST or None)
        if request.method == "POST":

            if form.is_valid():
                email = form.cleaned_data.get("email")
                password = form.cleaned_data.get("password")
                user = MyAuthBackend.authenticate(email=email, password=password)
                if user is not None:
                    login(request, user)
                    return redirect("/")
                else:
                    messages.info(request, "Invalid User")
            else:
                 messages.info(request, "Invalid Info")

    else:
         form = LoginForm()
    context = {
            'form':form
        }
    return render(request, 'authentication/login.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

authentication/templates/authentication/login.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block content %}


        <div class="container mt-5 p-5" >
            <h1>  Login</h1>

            <div class="card w-50">
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                
                        {{ form|crispy }}
                
                        <input type="submit" class="btn btn-primary mt-3" value="Login">
                    </form>
                    
                </div>
                <div class="container mt-2 mb-3">
                    <a href="{% url 'authentication:register' %}" >Create Account</a>
                </div>
            </div>
        </div>

        

{% endblock content %}

authentication/templates/authentication/register.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block content %}

 

    <div class="container mt-3 p-5" >
        <h1> Register</h1>

        <div class="card w-75">
            <div class="card-body w-100">
                <form action="" method="post">
                    {% csrf_token %}
            
                    {{ form|crispy }}
            
                    <input type="submit" class="btn btn-primary mt-3" value="Register">
                </form>
                
            </div>
            <div class="container mt-2 mb-3">
                <a href="{% url 'authentication:login' %}" >Already have an account?</a>
            </div>
        </div>
    </div>

{% endblock content %}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Bootstrap demo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>

<body>
    {% include 'navbar.html' %}
    {% if messages %}
    <div class="mt-5 pt-5">

    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    {% endfor %}
    {% endif %}
  </div>
    {% block content %}

    {% endblock %}


    

     <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">



    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="#" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2022 Copyright:
      <a href="#" target="_blank"> ecomm </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">AUTHBARR</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:register' %}">Register</a>
        </li>
      </ul>
    </div>
  </div>
</nav>